# Site settings
title: Amir Shahmoradi
address: The University of Texas at Austin
email: amir@ices.utexas.edu
description: > # this means to ignore newlines until "baseurl:"
  Institute for Computational Engineering and Sciences (ICES) <br>
  201 E 24th Street | POB 4.102 | Austin, TX 78712<br>
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: AmirShahmoradi
github_username:  shahmoradi
instagram_username: a.shahmoradi

# Build settings
markdown: kramdown
