# Site settings
title: Amir Shahmoradi, PhD
address: The University of Texas at Austin
email: >
  amir@physics.utexas.edu <br>
  shahmoradi@utexas.edu <br>
  amir@ices.utexas.edu <br>
description: > # this means to ignore newlines until "baseurl:"
  ICES Fellow, Institute for Computational Engineering and Sciences (ICES) <br>
  The University of Texas at Austin <br>
  201 E 24th Street | POB 6.328 | Austin, TX 78712 <br>
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
googles_username: shahmoradi
instagram_username: a.shahmoradi
linkedin_username: shahmoradi
twitter_username: AmirShahmoradi
github_username:  shahmoradi

# Build settings
markdown: kramdown
